services:

  postgres:
    image: postgres:13
    container_name: data_connector_postgres
    environment:
      POSTGRES_USER:     ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB:       ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backups:/backups
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - connector_net
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    image: shiv9777/data-connector-api:v1.9
    container_name: data_connector_api
    ports:
      - "8000:8000"
    volumes:
      - dags_volume:/app/dags
      - ./data:/app/data
      - ./Dataset:/app/dataset
      - ${WINDOWS_DOWNLOADS:-./data/uploads}:/app/uploads
      - ${WINDOWS_DOCUMENTS:-./Dataset}:/opt/airflow/dataset_win
      - .:/app/current_dir
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - connector_net
    restart: unless-stopped

  airflow-init:
    image: apache/airflow:2.7.0
    container_name: airflow_init
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - .env
    environment:
      AIRFLOW__CORE__EXECUTOR:             LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://${DB_USER}:${DB_PASSWORD}@postgres:5432/${DB_NAME}
      AIRFLOW__API__AUTH_BACKENDS:         airflow.api.auth.backend.basic_auth
      AIRFLOW__WEBSERVER__SECRET_KEY:      ${AIRFLOW__WEBSERVER__SECRET_KEY}
    command: >
      bash -c "airflow db migrate && airflow users create
      --username admin --password admin
      --firstname admin --lastname admin
      --role Admin --email admin@example.com"
    networks:
      - connector_net

  airflow-webserver:
    image: apache/airflow:2.7.0
    container_name: airflow_webserver
    env_file:
      - .env
    ports:
      - "8081:8080"
    volumes:
      - dags_volume:/opt/airflow/dags
      - ./data:/opt/airflow/data
      - ./Dataset:/opt/airflow/dataset
      - airflow_logs:/opt/airflow/logs
      - ${WINDOWS_DOCUMENTS:-./Dataset}:/opt/airflow/dataset_win   # ← same Windows folder in Airflow 
    depends_on:
      - airflow-init
    environment:
      AIRFLOW__CORE__EXECUTOR:             LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://${DB_USER}:${DB_PASSWORD}@postgres:5432/${DB_NAME}
      AIRFLOW__API__AUTH_BACKENDS:         airflow.api.auth.backend.basic_auth
      AIRFLOW__WEBSERVER__SECRET_KEY:      ${AIRFLOW__WEBSERVER__SECRET_KEY}
      _PIP_ADDITIONAL_REQUIREMENTS:        "boto3 polars openpyxl pandas"
      AWS_ACCESS_KEY_ID:                   ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY:               ${AWS_SECRET_ACCESS_KEY}
      AWS_REGION:                          ${AWS_REGION}
    command: webserver
    networks:
      - connector_net
    restart: unless-stopped

  airflow-scheduler:
    image: apache/airflow:2.7.0
    container_name: airflow_scheduler
    env_file:
      - .env
    volumes:
      - dags_volume:/opt/airflow/dags
      - ./data:/opt/airflow/data
      - ./Dataset:/opt/airflow/dataset
      - airflow_logs:/opt/airflow/logs
      - ${WINDOWS_DOCUMENTS:-./Dataset}:/opt/airflow/dataset_win   # ← same Windows folder in Airflow 
    depends_on:
      - airflow-webserver
    environment:
      AIRFLOW__CORE__EXECUTOR:             LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://${DB_USER}:${DB_PASSWORD}@postgres:5432/${DB_NAME}
      AIRFLOW__API__AUTH_BACKENDS:         airflow.api.auth.backend.basic_auth
      AIRFLOW__WEBSERVER__SECRET_KEY:      ${AIRFLOW__WEBSERVER__SECRET_KEY}
      _PIP_ADDITIONAL_REQUIREMENTS:        "boto3 polars openpyxl pandas"
      AWS_ACCESS_KEY_ID:                   ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY:               ${AWS_SECRET_ACCESS_KEY}
      AWS_REGION:                          ${AWS_REGION}
    command: scheduler
    networks:
      - connector_net
    restart: unless-stopped

volumes:
  postgres_data:
  airflow_logs:
  dags_volume:

networks:
  connector_net:
    driver: bridge
# services:

#   postgres:
#     image: postgres:13
#     container_name: data_connector_postgres
#     environment:
#       POSTGRES_USER:     ${DB_USER}
#       POSTGRES_PASSWORD: ${DB_PASSWORD}
#       POSTGRES_DB:       ${DB_NAME}
#     volumes:
#       - postgres_data:/var/lib/postgresql/data
#       - ./backups:/backups
#       - ./init.sql:/docker-entrypoint-initdb.d/init.sql
#     ports:
#       - "5432:5432"
#     networks:
#       - connector_net
#     restart: unless-stopped
#     healthcheck:
#       test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
#       interval: 10s
#       timeout: 5s
#       retries: 5

#   app:
#     # build: .
#     image: shiv9777/data-connector-api:v1.5
#     container_name: data_connector_api
#     ports:
#       - "8000:8000"
#     volumes:
#       - dags_volume:/app/dags          # ← shared volume
#       - ./data:/app/data
#       - ./Dataset:/app/dataset
#       # - C:/Users/LENOVO/Downloads:/app/uploads   # ← Downloads folder
#       # - C:/Users/LENOVO/Documents:/app/documents
#       - ${WINDOWS_DOWNLOADS}:/app/uploads
#       - ${WINDOWS_DOCUMENTS}:/app/documents

#       # - E:\Universal_data_connector_system\Dataset:/app/dataset_windows  # ← Windows path
#       - .:/app/current_dir  
#     env_file:
#       - .env
#     depends_on:
#       postgres:
#         condition: service_healthy
#     networks:
#       - connector_net
#     restart: unless-stopped

#   airflow-init:
#     image: apache/airflow:2.7.0
#     container_name: airflow_init
#     depends_on:
#       postgres:
#         condition: service_healthy
#     env_file:
#       - .env
#     environment:
#       AIRFLOW__CORE__EXECUTOR:             LocalExecutor
#       AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://${DB_USER}:${DB_PASSWORD}@postgres:5432/${DB_NAME}
#       AIRFLOW__API__AUTH_BACKENDS:         airflow.api.auth.backend.basic_auth
#       AIRFLOW__WEBSERVER__SECRET_KEY:      ${AIRFLOW__WEBSERVER__SECRET_KEY}
#     command: >
#       bash -c "airflow db migrate && airflow users create
#       --username admin --password admin
#       --firstname admin --lastname admin
#       --role Admin --email admin@example.com"
#     networks:
#       - connector_net

#   airflow-webserver:
#     image: apache/airflow:2.7.0
#     container_name: airflow_webserver
#     env_file:
#       - .env
#     ports:
#       - "8081:8080"
#     volumes:
#       - dags_volume:/opt/airflow/dags  # ← same shared volume
#       - ./data:/opt/airflow/data
#       - ./Dataset:/opt/airflow/dataset
#       - airflow_logs:/opt/airflow/logs
#     depends_on:
#       - airflow-init
#     environment:
#       AIRFLOW__CORE__EXECUTOR:             LocalExecutor
#       AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://${DB_USER}:${DB_PASSWORD}@postgres:5432/${DB_NAME}
#       AIRFLOW__API__AUTH_BACKENDS:         airflow.api.auth.backend.basic_auth
#       AIRFLOW__WEBSERVER__SECRET_KEY:      ${AIRFLOW__WEBSERVER__SECRET_KEY}
#       _PIP_ADDITIONAL_REQUIREMENTS:        "boto3 polars openpyxl pandas"
#       AWS_ACCESS_KEY_ID:                   ${AWS_ACCESS_KEY_ID}
#       AWS_SECRET_ACCESS_KEY:               ${AWS_SECRET_ACCESS_KEY}
#       AWS_REGION:                          ${AWS_REGION}
#     command: webserver
#     networks:
#       - connector_net
#     restart: unless-stopped

#   airflow-scheduler:
#     image: apache/airflow:2.7.0
#     container_name: airflow_scheduler
#     env_file:
#       - .env
#     volumes:
#       - dags_volume:/opt/airflow/dags  # ← same shared volume
#       - ./data:/opt/airflow/data
#       - ./Dataset:/opt/airflow/dataset
#       - airflow_logs:/opt/airflow/logs
#     depends_on:
#       - airflow-webserver
#     environment:
#       AIRFLOW__CORE__EXECUTOR:             LocalExecutor
#       AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://${DB_USER}:${DB_PASSWORD}@postgres:5432/${DB_NAME}
#       AIRFLOW__API__AUTH_BACKENDS:         airflow.api.auth.backend.basic_auth
#       AIRFLOW__WEBSERVER__SECRET_KEY:      ${AIRFLOW__WEBSERVER__SECRET_KEY}
#       _PIP_ADDITIONAL_REQUIREMENTS:        "boto3 polars openpyxl pandas"
#       AWS_ACCESS_KEY_ID:                   ${AWS_ACCESS_KEY_ID}
#       AWS_SECRET_ACCESS_KEY:               ${AWS_SECRET_ACCESS_KEY}
#       AWS_REGION:                          ${AWS_REGION}
#     command: scheduler
#     networks:
#       - connector_net
#     restart: unless-stopped

# volumes:
#   postgres_data:
#   airflow_logs:
#   dags_volume:        # ← new shared volume for DAGs

# networks:
#   connector_net:
#     driver: bridge
