

version: '3'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow

  airflow-init:
    image: apache/airflow:2.7.0
    depends_on:
      - postgres
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
      AIRFLOW__API__AUTH_BACKENDS: airflow.api.auth.backend.basic_auth
      AIRFLOW__WEBSERVER__SECRET_KEY: 08e07aa6e1e44d592baa7a46fe9c7b5c
    command: >
      bash -c "airflow db migrate && airflow users create \
      --username admin --password admin \
      --firstname admin --lastname admin \
      --role Admin --email admin@example.com"

  airflow-webserver:
    image: apache/airflow:2.7.0
    ports:
      - "8081:8080"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./data:/opt/airflow/data                               # relative data folder
      - E:\Universal_data_connector_system\data:/opt/airflow/user_data   # ✅ Windows path mounted
      - E:\Universal_data_connector_system\Dataset:/opt/airflow/dataset
    depends_on:
      - airflow-init
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
      AIRFLOW__API__AUTH_BACKENDS: airflow.api.auth.backend.basic_auth
      AIRFLOW__WEBSERVER__SECRET_KEY: 08e07aa6e1e44d592baa7a46fe9c7b5c
    command: webserver

  airflow-scheduler:
    image: apache/airflow:2.7.0
    depends_on:
      - airflow-webserver
    volumes:
      - ./dags:/opt/airflow/dags
      - ./data:/opt/airflow/data                               # relative data folder
      - E:\Universal_data_connector_system\data:/opt/airflow/user_data   # ✅ Windows path mounted
      - E:\Universal_data_connector_system\Dataset:/opt/airflow/dataset
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
      AIRFLOW__API__AUTH_BACKENDS: airflow.api.auth.backend.basic_auth
      AIRFLOW__WEBSERVER__SECRET_KEY: 08e07aa6e1e44d592baa7a46fe9c7b5c
    command: scheduler